key: groupdocs
display_name: GroupDocs
website: groupdocs.com
enabled: true

outputs_root: ../outputs

search_patterns:
  - "groupdocs.{product}"
  - "{product} for {platform}"
  - "groupdocs {product}"

repositories:
  - repo_key: "blog"
    repo_type: "blog"
    repo_url: "https://github.com/groupdocs/groupdocs-blog.git"
    branch: "master"
    scope: "all"
    root_subdir: "content/Groupdocs.Blog"
    include_globs:
      - "**/index.md"
