#!/usr/bin/env python3
"""
One-time (re-runnable) copy: reads the blog records already indexed by
agent_engine/content_indexer_agent (outputs/*/*/indexes/blog/all.jsonl -
committed, read only here, never regenerated by this script) and writes
our own content/dashboard_topic_index.json for the dashboard's
duplicate-topic check.

This is a DATA SNAPSHOT, not a live dependency on content_indexer_agent or
content_gap_agent - only the plain fields below (title/url/date) are kept;
nothing here imports from either agent's package. If those agents are ever
removed or split into their own repo, this script just can't be re-run
again - the dashboard_topic_index.json it already wrote keeps working, and
orchestrator.py appending one entry per newly generated post keeps it
current from there on, independent of this script or those agents.

Two data-quality issues found in the source JSONL and corrected here:
1. For aspose_cloud specifically, every product's all.jsonl turned out to
   contain a near-complete copy of the WHOLE brand's blog corpus (9630
   lines, only 1202 unique posts) - verified by comparing `id` across
   files. So records are deduped globally per brand by `id`, not trusted
   as scoped to the file they came from.
2. The record's own `product` field is unreliable - it reflects whichever
   per-product indexing run produced that copy of the file, not the
   post's real folder (verified: the same post appears under several
   different `product` values across files). `source_path` is trustworthy
   instead - the product slug is the path segment right after the brand's
   content-root prefix (stripped per SOURCE_PATH_PREFIX below).
3. The record's own `platform` field is NOT fully reliable either (it
   genuinely varies per post, not just echoing a query parameter - but
   three separate real failure cases were found and fixed via explicit
   title detection, overriding even an explicit source tag - see the
   comment above TITLE_PLATFORM_PATTERNS for all three).

Usage: python scripts/build_dashboard_topic_index.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Dict, List, Optional, Set

REPO_ROOT = Path(__file__).resolve().parents[1]
INDEXER_OUTPUTS = REPO_ROOT / "outputs"
PRODUCTS_DATA_DIR = REPO_ROOT / "content" / "productsData"
OUT_PATH = REPO_ROOT / "content" / "dashboard_topic_index.json"

# Indexer brand directory name -> dashboard brand id (blog-dashboard's
# lib/config.ts BRANDS keys). Bare "groupdocs" (groupdocs.com) is
# deliberately excluded - out of scope for the dashboard.
BRAND_MAP = {
    "aspose_cloud": "aspose.cloud",
    "aspose": "aspose.com",
    "conholdate_cloud": "conholdate.cloud",
    "conholdate": "conholdate.com",
    "groupdocs_cloud": "groupdocs.cloud",
}

# Fixed, single-product brands (every post lands in one folder, not
# per-product) - matches blog-dashboard/lib/config.ts's defaultProduct for
# these two. Skips product-slug parsing entirely.
FIXED_PRODUCT_BRANDS = {"conholdate.com": "Conholdate.Total", "conholdate.cloud": "Conholdate.Total"}

# source_path prefix to strip before reading the product slug, per brand -
# verified per brand (aspose_cloud's source_path includes the content-root
# folder name, the others start directly at the product slug).
SOURCE_PATH_PREFIX = {"aspose.cloud": "Aspose.Cloud/"}

# Indexer platform code -> dashboard platform label. Kept consistent with
# the equivalent mapping already in utils/metricsRecorder.py's start_job(),
# not reinvented. Audited 2026-10-01 against every brand's ACTUAL platform
# list in blog-dashboard/lib/config.ts (ASPOSE_CLOUD_PLATFORMS,
# GROUPDOCS_CLOUD_PLATFORMS, ASPOSE_COM_PLATFORMS, CONHOLDATE_*_PLATFORMS) -
# javascript/swift/apex/rust were real dashboard platform options missing
# here entirely (not even a PLATFORM_MAP code, let alone a title pattern).
PLATFORM_MAP = {
    "net": ".NET",
    "java": "Java",
    "python": "Python",
    "nodejs": "Node.js",
    "javascript": "JavaScript",
    "go": "Go",
    "php": "PHP",
    "android": "Android",
    "cpp": "C++",
    "ruby": "Ruby",
    "dart": "Dart",
    "perl": "Perl",
    "swift": "Swift",
    "apex": "Apex",
    "rust": "Rust",
}
# "general" (no specific platform detected in the post) has no dashboard
# platform of its own - such posts are folded into every platform actually
# seen for that same (brand, product) group, see _expand_platforms(). BUT
# first checked against TITLE_PLATFORM_PATTERNS below, and - unlike an
# earlier version of this script - that check overrides an EXPLICIT
# (non-"general") source platform too, not just "general". Started out
# general-only, on the theory that an explicit source tag was probably
# trustworthy; three separate, confirmed failure modes proved that wrong:
# (1) ~22% of general-tagged posts (473/2142) had an explicit platform in
# the title the source missed entirely (e.g. "Convert Word to TIFF in
# Ruby" tagged general, expanded into every one of Aspose.Words' platform
# buckets including PHP - a real false positive a user hit); (2) the
# source has no concept at all of aspose.com-specific categories like
# JasperReports - it tags that content with the underlying language
# instead (a user hit this too: a JasperReports post bucketed under
# Java); (3) titles containing "javascript" are frequently tagged plain
# "java" by the source - almost certainly because "java" is a literal
# substring of "javascript", a classic detection bug. A title that
# explicitly names a platform, via one of the anchored prepositional
# patterns below, is simply more trustworthy than this source field - so
# it wins regardless of what the source said.
#
# Patterns require one of these 4 prepositions immediately before the
# platform name - originally just "in", which turned out to be a real
# gap: sampled every "python"-mentioning title in the corpus and only
# 345/503 (69%) actually used "in python" - "using python" alone (120)
# nearly matched "for"+"with" combined, and would have gone entirely
# undetected (falling through to the "general"-expansion behavior this
# whole mechanism exists to avoid) without this broader prepositions list.
_PLATFORM_PREPOSITIONS = ["in", "for", "using", "with"]


def _platform_patterns(*name_regexes: str) -> List[str]:
    """One '\\b(in|for|using|with) <name>(?![\\w])' pattern per given
    spelling of a platform name (e.g. both "node.js" and "nodejs"). A
    trailing (?![\\w]) negative lookahead, NOT \\b - \\b matches a
    transition between a word and non-word character, which silently
    fails right after a name ending in a non-word char like "c#" or
    "c++" followed by a space (both sides of that position are already
    non-word, so there's no transition to match). Confirmed directly:
    \\bin c#\\b never matched "...in c# today" at all - this exact bug
    meant the .NET and C++ patterns had been silently non-functional
    since they were first written, never caught because no earlier test
    happened to use a C#/C++-titled example."""
    prep_group = "|".join(_PLATFORM_PREPOSITIONS)
    return [rf"\b(?:{prep_group})\s+{name}(?![\w])" for name in name_regexes]


TITLE_PLATFORM_PATTERNS: Dict[str, List[str]] = {
    ".NET": _platform_patterns(r"\.net") + _platform_patterns("c#"),
    "Java": _platform_patterns("java"),
    "Python": _platform_patterns("python"),
    "Node.js": _platform_patterns(r"node\.?js"),
    "JavaScript": _platform_patterns("javascript"),
    "PHP": _platform_patterns("php"),
    "Go": _platform_patterns("go", "golang"),
    "C++": _platform_patterns(r"c\+\+"),
    "Ruby": _platform_patterns("ruby"),
    "Android": _platform_patterns("android"),
    "Dart": _platform_patterns("dart"),
    "Perl": _platform_patterns("perl"),
    "Swift": _platform_patterns("swift"),
    "Apex": _platform_patterns("apex"),
    "Rust": _platform_patterns("rust"),
}

# aspose.com-specific "platform" choices that are really integration
# targets, not programming languages (see ASPOSE_COM_PLATFORMS in
# blog-dashboard's lib/config.ts) - the source indexer has no concept of
# these at all, so it tags this content with whatever underlying language
# it detects instead (e.g. a JasperReports post tagged "java", not
# "general" - a user hit this exact case: "Import SVG in PowerPoint
# Presentations in JasperReports" was bucketed under Java, so checking
# platform=JasperReports found nothing). Checked before
# TITLE_PLATFORM_PATTERNS (see _detect_platform_from_title) since these
# are more specific, distinctive compound terms.
INTEGRATION_PLATFORM_PATTERNS: Dict[str, List[str]] = {
    # "SQL Reporting" checked before "Reporting Services" - dict iteration
    # order matters here, "sql reporting services" contains "reporting
    # services" as a substring, so the more specific pattern must win.
    "SQL Reporting": [r"\bsql reporting\b"],
    "JasperReports": [r"\bjasperreports\b"],
    "Reporting Services": [r"\breporting services\b"],
    "SharePoint": [r"\bsharepoint\b"],
    "Xamarin": [r"\bxamarin\b"],
}
# ".NET Core" is deliberately NOT a separate bucket here - unlike the
# integration targets above, it's still just .NET (a runtime-version
# distinction, not a different topic), so it's folded into ".NET" on the
# matching side instead (blog-dashboard's lib/topic-duplicate.ts
# normalizePlatformForBucket) - consistent with how "Python via .NET" etc.
# already collapse to "Python" rather than getting their own bucket.


def _normalize_url(brand: str, raw_url: str) -> str:
    """content_indexer_agent's own `url` field is inconsistent - sometimes
    a full URL ("https://blog.aspose.com/gis/.../"), sometimes a bare
    "<brand>/path/" with no scheme and no "blog." subdomain. The bare form
    redirects to the brand's marketing site (not the blog subdomain) and
    404s there - confirmed live (a user hit exactly this, 404 on a match's
    link). 1,824/9,654 entries (19%) had the bare form, all consistently
    starting with "<brand>/" (verified, zero exceptions). Every other
    writer in this pipeline (orchestrator.py's append_new_post,
    backfill_missing_history.py, backfill_missing_products.py) already
    constructs the full form - this is the one holdout."""
    if not raw_url or raw_url.startswith("http"):
        return raw_url
    prefix = f"{brand}/"
    if raw_url.startswith(prefix):
        return f"https://blog.{brand}/{raw_url[len(prefix):]}"
    return raw_url  # unexpected shape - leave untouched rather than guess


def _detect_platform_from_title(title: str) -> Optional[str]:
    """Checks INTEGRATION_PLATFORM_PATTERNS first (more specific compound
    terms), then TITLE_PLATFORM_PATTERNS. Both tiers override even an
    explicit, non-"general" source platform - see the comment above
    TITLE_PLATFORM_PATTERNS for why that's safe and necessary."""
    t = title.lower()
    for patterns_dict in (INTEGRATION_PLATFORM_PATTERNS, TITLE_PLATFORM_PATTERNS):
        for platform, patterns in patterns_dict.items():
            for pattern in patterns:
                if re.search(pattern, t):
                    return platform
    return None

_PRODUCT_NAME_CACHE: Dict[str, Dict[str, str]] = {}


def _load_product_names(brand: str) -> Dict[str, str]:
    """urlPrefix -> display product name, e.g. 'cad' -> 'Aspose.CAD'.
    Derived from each entry's Category field ('X Cloud Product Family' /
    'X Product Family' -> 'X'), deduped by urlPrefix (several platform
    variants of a product share one urlPrefix)."""
    if brand in _PRODUCT_NAME_CACHE:
        return _PRODUCT_NAME_CACHE[brand]
    path = PRODUCTS_DATA_DIR / f"{brand}.json"
    out: Dict[str, str] = {}
    if path.exists():
        data = json.loads(path.read_text(encoding="utf-8"))
        for entry in data:
            prefix = entry.get("urlPrefix")
            if not prefix or prefix in out:
                continue
            name = entry.get("Category", "") or ""
            for suffix in (" Cloud Product Family", " Product Family"):
                if name.endswith(suffix):
                    name = name[: -len(suffix)]
                    break
            out[prefix] = name or prefix
    _PRODUCT_NAME_CACHE[brand] = out
    return out


def _derive_product(brand: str, rec: dict) -> str:
    if brand in FIXED_PRODUCT_BRANDS:
        return FIXED_PRODUCT_BRANDS[brand]
    source_path = rec.get("source_path") or ""
    prefix = SOURCE_PATH_PREFIX.get(brand, "")
    if prefix and source_path.startswith(prefix):
        source_path = source_path[len(prefix):]
    slug = source_path.split("/")[0] if source_path else (rec.get("product") or "")
    return _load_product_names(brand).get(slug, slug)


def _resolve_platform(rec: dict, title: str) -> Optional[str]:
    """The final display platform for one record, or None if it's still
    unresolved ("general", with no title match either) - callers expand an
    unresolved record into every platform seen elsewhere for the same
    product (see build_index). Title detection is checked first and wins
    over an explicit source tag - see the comment above
    TITLE_PLATFORM_PATTERNS for the three confirmed failure modes that
    made the source field untrustworthy on its own."""
    title_platform = _detect_platform_from_title(title)
    if title_platform:
        return title_platform
    source_code = rec.get("platform")
    if source_code not in (None, "general"):
        return PLATFORM_MAP.get(source_code, source_code)
    return None


# Beyond this many distinct resolved platforms for one product, an
# unresolved ("general") post stays in a single shared "general" bucket
# instead of fanning out to all of them. Found via Aspose.Total (a
# bundle/announcement product, ~1,145 posts): only a handful resolved to a
# specific platform by title, so the other ~1,135 - almost certainly
# genuinely cross-cutting "what's new across Aspose" content, not
# ambiguous-among-a-few-candidates - got expanded into all 10 resolved
# platforms, ~8,000 (bucket,post) pairs from one product alone. Past this
# threshold, "general" more likely means truly cross-platform than unknown.
MAX_EXPANSION_PLATFORMS = 5


def platforms_for_unresolved(platforms_in_group: List[str]) -> List[str]:
    if not platforms_in_group or len(platforms_in_group) > MAX_EXPANSION_PLATFORMS:
        return ["general"]
    return platforms_in_group


def _load_unique_records(indexer_brand: str) -> List[dict]:
    """All records for one indexer brand directory, deduped by `id` across
    however many of its per-product files happen to overlap (see module
    docstring, issue 1)."""
    seen: Dict[str, dict] = {}
    for jsonl_path in sorted((INDEXER_OUTPUTS / indexer_brand).glob("*/indexes/blog/all.jsonl")):
        for line in jsonl_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            rec_id = rec.get("id") or rec.get("source_path") or rec.get("title")
            if rec_id and rec_id not in seen:
                seen[rec_id] = rec
    return list(seen.values())


def build_index() -> Dict[str, List[dict]]:
    index: Dict[str, List[dict]] = {}
    total = 0
    for indexer_brand, brand in BRAND_MAP.items():
        brand_dir = INDEXER_OUTPUTS / indexer_brand
        if not brand_dir.exists():
            continue
        records = _load_unique_records(indexer_brand)

        # Group by (derived) product first, so "general" posts fold only
        # into platforms genuinely seen for THAT product, not every
        # platform the brand offers anywhere.
        by_product: Dict[str, List[dict]] = {}
        for rec in records:
            if not (rec.get("title") or "").strip():
                continue
            by_product.setdefault(_derive_product(brand, rec), []).append(rec)

        for product, prod_records in by_product.items():
            # Pass 1: resolve each record's final platform (title
            # detection first, falling back to a trustworthy explicit
            # source tag - see _resolve_platform). None means still
            # unresolved ("general", no title match either).
            resolved = []
            for rec in prod_records:
                title = rec["title"].strip()
                entry = {"title": title, "url": _normalize_url(brand, rec.get("url", "")), "date": rec.get("published_date", "")}
                resolved.append((entry, _resolve_platform(rec, title)))

            # The platforms genuinely seen for THIS product, from pass 1's
            # results (not raw source tags) - an unresolved record folds
            # into every one of these, not every platform the brand offers
            # anywhere, and not into platforms that only exist because of
            # OTHER unresolved records being folded in circularly.
            platforms_in_group = sorted({p for _, p in resolved if p})

            seen_per_bucket: Dict[str, Set[str]] = {}
            for entry, final_platform in resolved:
                dedupe_key = entry["url"] or entry["title"]
                platforms = [final_platform] if final_platform else platforms_for_unresolved(platforms_in_group)
                for platform in platforms:
                    key = f"{brand}|{product}|{platform}"
                    bucket_seen = seen_per_bucket.setdefault(key, set())
                    if dedupe_key in bucket_seen:
                        continue
                    bucket_seen.add(dedupe_key)
                    index.setdefault(key, []).append(entry)
                    total += 1

    print(f"Indexed {total} (bucket, post) pairs across {len(index)} buckets.")
    return index


def main() -> None:
    index = build_index()
    OUT_PATH.write_text(
        json.dumps(index, indent=2, ensure_ascii=False, sort_keys=True),
        encoding="utf-8",
    )
    print(f"Wrote {OUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
