#!/usr/bin/env python3
"""
One-time (re-runnable) copy: reads the blog records already indexed by
agent_engine/content_indexer_agent (outputs/*/*/indexes/blog/all.jsonl -
committed, read only here, never regenerated by this script) and writes
our own content/dashboard_topic_index.json for the dashboard's
duplicate-topic check.

This is a DATA SNAPSHOT, not a live dependency on content_indexer_agent or
content_gap_agent - only the plain fields below (title/url/date) are kept;
nothing here imports from either agent's package. If those agents are ever
removed or split into their own repo, this script just can't be re-run
again - the dashboard_topic_index.json it already wrote keeps working, and
orchestrator.py appending one entry per newly generated post keeps it
current from there on, independent of this script or those agents.

Two data-quality issues found in the source JSONL and corrected here:
1. For aspose_cloud specifically, every product's all.jsonl turned out to
   contain a near-complete copy of the WHOLE brand's blog corpus (9630
   lines, only 1202 unique posts) - verified by comparing `id` across
   files. So records are deduped globally per brand by `id`, not trusted
   as scoped to the file they came from.
2. The record's own `product` field is unreliable - it reflects whichever
   per-product indexing run produced that copy of the file, not the
   post's real folder (verified: the same post appears under several
   different `product` values across files). `source_path` is trustworthy
   instead - the product slug is the path segment right after the brand's
   content-root prefix (stripped per SOURCE_PATH_PREFIX below).
The record's own `platform` field IS reliable (genuine per-post
diversity confirmed, not just echoing a query parameter).

Usage: python scripts/build_dashboard_topic_index.py
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List, Set

REPO_ROOT = Path(__file__).resolve().parents[1]
INDEXER_OUTPUTS = REPO_ROOT / "outputs"
PRODUCTS_DATA_DIR = REPO_ROOT / "content" / "productsData"
OUT_PATH = REPO_ROOT / "content" / "dashboard_topic_index.json"

# Indexer brand directory name -> dashboard brand id (blog-dashboard's
# lib/config.ts BRANDS keys). Bare "groupdocs" (groupdocs.com) is
# deliberately excluded - out of scope for the dashboard.
BRAND_MAP = {
    "aspose_cloud": "aspose.cloud",
    "aspose": "aspose.com",
    "conholdate_cloud": "conholdate.cloud",
    "conholdate": "conholdate.com",
    "groupdocs_cloud": "groupdocs.cloud",
}

# Fixed, single-product brands (every post lands in one folder, not
# per-product) - matches blog-dashboard/lib/config.ts's defaultProduct for
# these two. Skips product-slug parsing entirely.
FIXED_PRODUCT_BRANDS = {"conholdate.com": "Conholdate.Total", "conholdate.cloud": "Conholdate.Total"}

# source_path prefix to strip before reading the product slug, per brand -
# verified per brand (aspose_cloud's source_path includes the content-root
# folder name, the others start directly at the product slug).
SOURCE_PATH_PREFIX = {"aspose.cloud": "Aspose.Cloud/"}

# Indexer platform code -> dashboard platform label. Kept consistent with
# the equivalent mapping already in utils/metricsRecorder.py's start_job(),
# not reinvented.
PLATFORM_MAP = {
    "net": ".NET",
    "java": "Java",
    "python": "Python",
    "nodejs": "Node.js",
    "go": "Go",
    "php": "PHP",
    "android": "Android",
    "cpp": "C++",
    "ruby": "Ruby",
    "dart": "Dart",
    "perl": "Perl",
}
# "general" (no specific platform detected in the post) has no dashboard
# platform of its own - such posts are folded into every platform actually
# seen for that same (brand, product) group, see _expand_platforms().

_PRODUCT_NAME_CACHE: Dict[str, Dict[str, str]] = {}


def _load_product_names(brand: str) -> Dict[str, str]:
    """urlPrefix -> display product name, e.g. 'cad' -> 'Aspose.CAD'.
    Derived from each entry's Category field ('X Cloud Product Family' /
    'X Product Family' -> 'X'), deduped by urlPrefix (several platform
    variants of a product share one urlPrefix)."""
    if brand in _PRODUCT_NAME_CACHE:
        return _PRODUCT_NAME_CACHE[brand]
    path = PRODUCTS_DATA_DIR / f"{brand}.json"
    out: Dict[str, str] = {}
    if path.exists():
        data = json.loads(path.read_text(encoding="utf-8"))
        for entry in data:
            prefix = entry.get("urlPrefix")
            if not prefix or prefix in out:
                continue
            name = entry.get("Category", "") or ""
            for suffix in (" Cloud Product Family", " Product Family"):
                if name.endswith(suffix):
                    name = name[: -len(suffix)]
                    break
            out[prefix] = name or prefix
    _PRODUCT_NAME_CACHE[brand] = out
    return out


def _derive_product(brand: str, rec: dict) -> str:
    if brand in FIXED_PRODUCT_BRANDS:
        return FIXED_PRODUCT_BRANDS[brand]
    source_path = rec.get("source_path") or ""
    prefix = SOURCE_PATH_PREFIX.get(brand, "")
    if prefix and source_path.startswith(prefix):
        source_path = source_path[len(prefix):]
    slug = source_path.split("/")[0] if source_path else (rec.get("product") or "")
    return _load_product_names(brand).get(slug, slug)


def _expand_platforms(platform_code: str, platforms_in_group: Set[str]) -> List[str]:
    if platform_code and platform_code != "general":
        return [PLATFORM_MAP.get(platform_code, platform_code)]
    if not platforms_in_group:
        return ["general"]
    return sorted(PLATFORM_MAP.get(p, p) for p in platforms_in_group)


def _load_unique_records(indexer_brand: str) -> List[dict]:
    """All records for one indexer brand directory, deduped by `id` across
    however many of its per-product files happen to overlap (see module
    docstring, issue 1)."""
    seen: Dict[str, dict] = {}
    for jsonl_path in sorted((INDEXER_OUTPUTS / indexer_brand).glob("*/indexes/blog/all.jsonl")):
        for line in jsonl_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            rec_id = rec.get("id") or rec.get("source_path") or rec.get("title")
            if rec_id and rec_id not in seen:
                seen[rec_id] = rec
    return list(seen.values())


def build_index() -> Dict[str, List[dict]]:
    index: Dict[str, List[dict]] = {}
    total = 0
    for indexer_brand, brand in BRAND_MAP.items():
        brand_dir = INDEXER_OUTPUTS / indexer_brand
        if not brand_dir.exists():
            continue
        records = _load_unique_records(indexer_brand)

        # Group by (derived) product first, so "general" posts fold only
        # into platforms genuinely seen for THAT product, not every
        # platform the brand offers anywhere.
        by_product: Dict[str, List[dict]] = {}
        for rec in records:
            if not (rec.get("title") or "").strip():
                continue
            by_product.setdefault(_derive_product(brand, rec), []).append(rec)

        for product, prod_records in by_product.items():
            platforms_in_group = {r.get("platform") for r in prod_records if r.get("platform") not in (None, "general")}
            seen_per_bucket: Dict[str, Set[str]] = {}
            for rec in prod_records:
                title = rec["title"].strip()
                entry = {"title": title, "url": rec.get("url", ""), "date": rec.get("published_date", "")}
                dedupe_key = entry["url"] or title
                for platform in _expand_platforms(rec.get("platform"), platforms_in_group):
                    key = f"{brand}|{product}|{platform}"
                    bucket_seen = seen_per_bucket.setdefault(key, set())
                    if dedupe_key in bucket_seen:
                        continue
                    bucket_seen.add(dedupe_key)
                    index.setdefault(key, []).append(entry)
                    total += 1

    print(f"Indexed {total} (bucket, post) pairs across {len(index)} buckets.")
    return index


def main() -> None:
    index = build_index()
    OUT_PATH.write_text(
        json.dumps(index, indent=2, ensure_ascii=False, sort_keys=True),
        encoding="utf-8",
    )
    print(f"Wrote {OUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
